### ISSUE TITLE
Downgrade linux kernel to 3.16 version

### ISSUE THREAD

**Issue by andreyvpng** [pbrisbin/downgrade#126]
How can I downgrade Linux to 3.16?
When I start `` downgrade linux ``, I see the minimum version 4.20
```
 » downgrade linux                                             1 ↵ andrey@asus
Available packages:

     1)  linux    4.20.1.arch1   1  x86_64  (remote)
     2)  linux    4.20.2.arch1   1  x86_64  (remote)
     3)  linux    4.20.3.arch1   1  x86_64  (remote)
     .....
```

I using Arch. Downgrade installing from aur

**Comment by atreyasha** [comment]
Hi @andreyvpng. By default, `downgrade linux` will check both the A.L.A and your local cache for the `linux` kernel package. I am assuming `linux` 3.16 is not in your caches, so `downgrade` outputs the results from the search in the remote A.L.A. As you can verify here (https://archive.archlinux.org/packages/l/linux/), the oldest version available is `4.20.*`.

If you want to grab an even older version, you could consider restoring packages back to a specific date as per instructions here (https://wiki.archlinux.org/index.php/Arch_Linux_Archive).

**Comment by atreyasha** [comment]
Closing this issue as it is not specific to features of `downgrade`. Feel free to re-open if anything related comes up.

**Comment by andreyvpng** [comment]
thanks for answer @atreyasha !
