### ISSUE TITLE
Changing default branch

### ISSUE THREAD

**Issue by pbrisbin** [pbrisbin/downgrade#150]
@atreyasha I'd like to rename the default branch to `main`. I've been doing it across all my projects and it goes very smoothly, thanks to GitHub's recent support for renames.

I will wait until any open PRs are merged, but I wonder if there are any other possible disruptions / necessary changes you could think of. Does the PKGBUILD reference `master` at all?

**Comment by atreyasha** [comment]
> Does the PKGBUILD reference master at all?

No reference to `master` or any default branch

```shell
# shellcheck disable=SC2034
# shellcheck disable=SC2154
# Author: Patrick Brisbin <pbrisbin@gmail.com>
pkgname=downgrade
pkgver=9.0.0
pkgrel=1
pkgdesc="Bash script for downgrading one or more packages to a version in your cache or the A.L.A."
arch=('any')
url="https://github.com/pbrisbin/$pkgname"
license=('GPL')
source=("downgrade-v$pkgver.tar.gz::https://github.com/pbrisbin/$pkgname/archive/v$pkgver.tar.gz")
depends=('pacman-contrib') # pacsort
optdepends=('sudo: for installation via sudo')

package() {
  cd "$pkgname-$pkgver" || exit 1

  make DESTDIR="$pkgdir" PREFIX=/usr install
}
md5sums=('f37e1c3c70d6b1292c7ea3499eebab87')
```

**Comment by atreyasha** [comment]
Tried out a local test by forking, changing default branch to `main` and installing a new release with a custom `PKGBUILD`.

Everything works fine, so we should be good to go :+1:

The relevant line in the `PKGBUILD` is the one defining the `source` variable. Since the branch is not defined in the URL, I believe GitHub would route you to the default branch which is exactly as intended.

**Comment by pbrisbin** [comment]
Wow, thanks for the thorough testing! I see no open PRs right now so I'm going to make the change. If you visit the repository page for this project after I've done it, you'll see a little notification with commands to run locally.

**Comment by pbrisbin** [comment]
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
