### ISSUE TITLE
That you can downgrade to versions you have in cache

### ISSUE THREAD

**Issue by Toadfield** [pbrisbin/downgrade#165]
### Checklist

- [x] No duplicate issues/PRs
- [x] Are you running the latest `downgrade` release from the [AUR](https://aur.archlinux.org/packages/downgrade/)?

### Background

Sometimes when I try to downgrade a package then there aren't any versions I can downgrade to.
But I still have packages in the cache and I want to be able to downgrade to them via downgrade.

### Proposed feature
That when you do "downgrade >package name<" in terminal,that then it also lists packages that you have in cache.

**Comment by atreyasha** [comment]
Hi @Toadfield, thanks for the feature request.

This feature is already implemented in `downgrade`. Closing this issue as there is no feature to add or modify.

--

If you are unable to see the cached versions of packages in the selection menu, this implies that the cached packages could not be found during the search process. There could be several reasons for this, which we can try to debug.

Some things you could try to fix this locally:

1. What is the directory where your caches are stored? This normally defaults to `/var/cache/pacman/pkg`, but I suspect this is different in your use-case.

2. Once you know this directory, try the following command:

    ```
    # downgrade --pacman-cache /path/to/cache/dir <pkg_to_downgrade>
    ```
