### ISSUE TITLE
Packages with a slash in the name cannot be downgraded

### ISSUE THREAD

**Issue by nailuj29** [pbrisbin/downgrade#184]
### Checklist

- [x] No duplicate issues/PRs
- [x] Are you running the latest `downgrade` release from the [AUR](https://aur.archlinux.org/packages/downgrade/)?

### Environment

* System information:

Linux nailuj29 5.15.21-1-MANJARO #1 SMP PREEMPT Sun Feb 6 12:21:42 UTC 2022 x86_64 GNU/Linux
* Downgrade version:

```
Downgrading from A.L.A. is disabled on the stable branch. To override this behavior, set DOWNGRADE_FROM_ALA to 1 .
See https://wiki.manjaro.org/index.php/Downgrading_packages  for more details.
```
11.0.0

### Description

Package downgrade fails when package name has a slash
### Steps to Reproduce

1. First Step
`downgrade 'extra/boost-libs'`

### Expected behavior

The package is downgraded
### Actual behavior
```
sed: -e expression #1, char 40: Unmatched ( or \(
No results found
Unable to downgrade extra/boost-libs
```

**Comment by atreyasha** [comment]
Hi @nailuj29. In regards to downgrading `boost-libs`, just downgrading with the package name should do the trick. In other words, specifying the repository `extra` here is unnecessary:

```
# downgrade boost-libs
```

Also package names containing slashes are not permitted as per the Arch package [guidelines](https://wiki.archlinux.org/title/Arch_package_guidelines), so we would not need to account for this.

@pbrisbin on the other hand, I think providing a slash (or any other disallowed character) in the package name should ideally lead to an error message and not the `sed` error message `sed: -e expression ...`. I think this might have to do with these special characters not being escapred properly before the regular expression. Do you think it makes sense to escape the package entries beforehand with something like `printf "%q"`?

**Comment by pbrisbin** [comment]
> I think providing a slash (or any other disallowed character) in the package name should ideally lead to a standard error message and not...

Agreed with the principle. In this case, it could be better to respond to the failure instead of aiming to prevent it, something like:

```sh
if ! { whatever contains the sed }; then
  echo "{better error message}. $input might be invalid?"
  exit 1
fi
```

Or, if `/` is by far the most common mistake, and it's a problem because we do `s/.../`, we could do anything else, such as `s|...|` or `s%...%`.

**Comment by nailuj29** [comment]
@atreyasha 
When I run `downgrade boost-libs` it outputs this and fails.
```

Downgrading from A.L.A. is disabled on the stable branch. To override this behavior, set DOWNGRADE_FROM_ALA to 1 .
See https://wiki.manjaro.org/index.php/Downgrading_packages  for more details.

No results found
Unable to downgrade boost-libs
```

**Comment by pbrisbin** [comment]
That's something Manjaro does. I suggest asking in their forums.
