### ISSUE TITLE
download packages to pacman cache?

### ISSUE THREAD

**Issue by anntzer** [pbrisbin/downgrade#36]
It would be nice if downloaded packages went to the pacman cache (to avoid repeated downloads when switching back and forth between two versions, e.g. when debugging), or at least to a temporary directory in order to avoid polluting $pwd.

**Comment by pbrisbin** [comment]
Putting it in the cache sounds useful, but not super simple as you'd have to read the value out of the config file.

If someone were to open this as a PR, I'd definitely review and likely merge. Unfortunately, I don't see myself getting to it soon.

**Comment by anntzer** [comment]
The standard `paccache` utility contains the following blurb:
```
get_cachedir_from_config() {
	local key value

	while IFS=$'= \t' read -r key value _; do
		if [[ $key = CacheDir ]]; then
			echo "$value"
			return 0
		fi
	done <"$1"

	return 1
}
```
(to be used as `get_cachedir_from_config /etc/pacman.conf`)

Apparently there is no provision for handling spaces in cache paths (even in pacman itself, which is written in C), so you don't need to worry about it.

The only issue is that this only returns the first cache, whereas CacheDir can technically be a list of paths (in which case `get_cachedir_from_config` returns the first path, but pacman will read from all of them in order but write to the first **writable** dir).  I honestly think you don't need to support the case where the first writable dir is not the first dir :-)
