### ISSUE TITLE
Default ARM_URL is offline

### ISSUE THREAD

**Issue by FadeMind** [pbrisbin/downgrade#37]
Default used ARM_URL `http://repo-arm.archlinuxcn.org` site is offline.
Is It  available any mirror?
Debug: https://pastebin.com/raw/3idnpvuE

**Comment by pbrisbin** [comment]
I've created at branch in #38 that scrapes https://archive.archlinux.org directly, instead of relying on repo-arm.archilnuxcn.org's search feature.

Please do try it and let me know if it's works for you. I can release it over the weekend.

**Comment by FadeMind** [comment]
@pbrisbin 

Now working fine thank you.

$ downgrade p7zip
Available packages:

   1) p7zip-9.38.1-4-x86_64.pkg.tar.xz (local)
   2) p7zip-9.38.1-4-x86_64.pkg.tar.xz (remote)
   3) p7zip-9.38.1-3-x86_64.pkg.tar.xz (remote)
   4) p7zip-9.38.1-2-x86_64.pkg.tar.xz (remote)
   5) p7zip-9.38.1-1-x86_64.pkg.tar.xz (remote)
   6) p7zip-9.38-3-x86_64.pkg.tar.xz (remote)
   7) p7zip-9.38-2-x86_64.pkg.tar.xz (remote)
   8) p7zip-9.38-1-x86_64.pkg.tar.xz (remote)
   9) p7zip-9.20.1-9-x86_64.pkg.tar.xz (remote)
  10) p7zip-9.20.1-8-x86_64.pkg.tar.xz (remote)
  11) p7zip-9.20.1-7-x86_64.pkg.tar.xz (remote)

select a package by number: 
$ downgrade dolphin
Available packages:

   1) dolphin-15.12.1-1-x86_64.pkg.tar.xz (local)
   2) dolphin-15.12.1-1-x86_64.pkg.tar.xz (remote)
   3) dolphin-15.12.0-2-x86_64.pkg.tar.xz (remote)
   4) dolphin-15.12.0-1-x86_64.pkg.tar.xz (remote)
   5) dolphin-15.11.90-2-x86_64.pkg.tar.xz (remote)
   6) dolphin-15.11.90-1-x86_64.pkg.tar.xz (remote)
   7) dolphin-15.11.80-1-x86_64.pkg.tar.xz (remote)
   8) dolphin-15.08.3-3-x86_64.pkg.tar.xz (remote)
   9) dolphin-15.08.3-2-x86_64.pkg.tar.xz (remote)
  10) dolphin-15.08.3-1-x86_64.pkg.tar.xz (remote)
  11) dolphin-15.08.2-1-x86_64.pkg.tar.xz (remote)
  12) dolphin-15.08.1-1-x86_64.pkg.tar.xz (remote)
  13) dolphin-15.08.0-2-x86_64.pkg.tar.xz (remote)
  14) dolphin-15.08.0-1-x86_64.pkg.tar.xz (remote)
  15) dolphin-15.07.90-2-x86_64.pkg.tar.xz (remote)
  16) dolphin-15.07.80-2-x86_64.pkg.tar.xz (remote)
  17) dolphin-15.07.80-1-x86_64.pkg.tar.xz (remote)

select a package by number:      
[tomasz@arch downgrade]$

**Comment by pbrisbin** [comment]
Fixed version released as 5.2.0.

**Comment by marcvangend** [comment]
Is this really / still fixed? I'm running version 5.2.0 but downgrade can't seem to find remote packages, only local:

```
$ downgrade ansible
Available packages:

   1) ansible-2.0.0.2-2-any.pkg.tar.xz (local)
   2) ansible-2.0.0.1-1-any.pkg.tar.xz (local)
   3) ansible-1.9.4-1-any.pkg.tar.xz (local)

select a package by number: 
```

**Comment by FadeMind** [comment]
@marcvangend CONFIRMED.

But another package is fine:

[tomasz@arch ~]$ downgrade ansible 
Available packages:

   1) ansible-2.0.0.2-2-any.pkg.tar.xz (local)

select a package by number: 
[tomasz@arch ~]$ downgrade konsole
Available packages:

   1) konsole-15.12.1-1-x86_64.pkg.tar.xz (remote)
   2) konsole-15.12.0-1-x86_64.pkg.tar.xz (remote)
   3) konsole-15.11.90-2-x86_64.pkg.tar.xz (remote)
   4) konsole-15.11.90-1-x86_64.pkg.tar.xz (remote)
   5) konsole-15.11.80-1-x86_64.pkg.tar.xz (remote)
   6) konsole-15.08.3-2-x86_64.pkg.tar.xz (remote)
   7) konsole-15.08.3-1-x86_64.pkg.tar.xz (remote)
   8) konsole-15.08.2-1-x86_64.pkg.tar.xz (remote)
   9) konsole-15.08.1-1-x86_64.pkg.tar.xz (remote)
  10) konsole-15.08.0-1-x86_64.pkg.tar.xz (remote)
  11) konsole-15.07.90-1-x86_64.pkg.tar.xz (remote)
  12) konsole-15.07.80-1-x86_64.pkg.tar.xz (remote)
  13) konsole-15.04.3-1-x86_64.pkg.tar.xz (remote)
  14) konsole-15.04.2-1-x86_64.pkg.tar.xz (remote)
  15) konsole-15.04.1-1-x86_64.pkg.tar.xz (remote)
  16) konsole-15.04.0-1-x86_64.pkg.tar.xz (remote)
  17) konsole-15.03.97-1-x86_64.pkg.tar.xz (remote)
  18) konsole-15.03.95-1-x86_64.pkg.tar.xz (remote)
  19) konsole-15.03.90-1-x86_64.pkg.tar.xz (remote)
  20) konsole-14.12.3-1-x86_64.pkg.tar.xz (remote)
  21) konsole-14.12.2-1-x86_64.pkg.tar.xz (remote)
  22) konsole-14.12.1-1-x86_64.pkg.tar.xz (remote)

select a package by number: 
[tomasz@arch ~]$

**Comment by pbrisbin** [comment]
Sorry folks. When I made this fix, I didn't correctly handle `-any` packages. Will fix today.

**Comment by marcvangend** [comment]
Thanks for the quick responses, @FadeMind and @pbrisbin !

Meanwhile, if anyone is looking for a quick-and-dirty workaround: I manually downloaded the desired package from the ALA and placed it in `/var/cache/pacman/pkg/` to make it show up as a locally available package.

**Comment by pbrisbin** [comment]
@marcvangend please try v5.2.1

**Comment by marcvangend** [comment]
Works like a charm! Thank you.
