### ISSUE TITLE
Replace references of A.R.M with A.L.A

### ISSUE THREAD

**Issue by polarathene** [pbrisbin/downgrade#56]
Arch Linux Rollback Machine(A.R.M) is [now known as Arch Linux Archive(A.L.A)](https://wiki.archlinux.org/index.php/Arch_Linux_Archive), run a find & replace on the keyword to reflect this please. README.md being an obvious one.

**Comment by pbrisbin** [comment]
Oh man I can't keep up!

Thanks for reporting, I will get to this when I can. FWIW, a PR would certainly speed up the process.

**Comment by pbrisbin** [comment]
Fixed by 386b5fcd, will release soon.
