### ISSUE TITLE
Usage for multiple packages is not clear

### ISSUE THREAD

**Issue by droidmonkey** [pbrisbin/downgrade#69]
The current usage looks like ```usage: downgrade <pkg>, ... [-- <pacman options>]``` but one should NOT put in commas when listing multiple package names. Usage should look like: 

```usage: downgrade <pkg> [<pkg>]... [-- <pacman options>]```

**Comment by pbrisbin** [comment]
Thanks for reporting, I'm happy to make that change.

It sounds like your belief is that it's reasonable to assume the user knows that `<`, `>`, `[`, and `]` are all "decoration" not to be typed, but not `,`. Is that right?

Do you happen to have any references for this, or the rules for formatting usage instructions generally? I've looked in the past and had trouble finding that, and would love to following something "official" if possible.

**Comment by droidmonkey** [comment]
Sure, it is defined in the POSIX standard:

http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html

**Comment by pbrisbin** [comment]
Oh, thank you for that reference!

Reading it, it seems like the usage should actually be this:

```
usage: downgrade <pkg> [pkg...] [-- pacman_option...]
```

There are some differences with your latest suggestion, so let me know if you feel strongly about anything in your version. Otherwise, I'll get this change in sometime over the next week.

**Comment by droidmonkey** [comment]
I think it can go either way, but your syntax more closely aligns to ```utility_name -f option_argument [-f option_argument]...``` on my reading
