### ISSUE TITLE
Add "-maxdepth 1" option to find command

### ISSUE THREAD

**Issue by Cody-Learner** [pbrisbin/downgrade#70]
I've a dedicated partition mounted to /var/cache/pacman/pkg that contains a lost-found directory. A leftover from ARM project ending notice.

Find warns of needing permission for lost-found.
I've added `-maxdepth 1` to find command downgrade script, line 117.
Seems this addition would not cause any issues for more conventional configurations?

**Comment by pbrisbin** [comment]
I think that seems reasonable. I'm not 100% sure, but I don't think pacman puts anything not at top-level of the cache.

I won't have time to implement this for a week or more, but I would happily accept a PR for it.

**Comment by Cody-Learner** [comment]
A PR is..... pull request? Sorry, but pulling off a proper pull request is getting outside my "cowboy coder" knowledge base!  I'm always glad to learn something new though. I'll see what I can find to try to figure this out.  It's about time I get myself up to speed on this.

**Comment by pbrisbin** [comment]
Merged, thanks!
