### ISSUE TITLE
No documentation of - and + except in issue or git log

### ISSUE THREAD

**Issue by alexanderkogan** [pbrisbin/downgrade#80]
Please add a description about the - and + indicators in the "Available packages" overview to the man page.

**Comment by pbrisbin** [comment]
Thanks for the report. I'll do this when I can, but just FYI if you were able to propose something by PR that would make it happen faster.

**Comment by alexanderkogan** [comment]
Sure, I'll see what I can do. I just wasn't sure about the style you want to have.
