### ISSUE TITLE
Downgrade via version number on command line

### ISSUE THREAD

**Issue by Gibbz** [pbrisbin/downgrade#82]
Id like to be able to use downgrade to work with a supplied version number on the commandline.
For example i want to downgrade wine to version 4.9 which downgrade shows in the second column.
For example:
downgrade wine-4.9

And also an option like 'pacaur --noconfirm --needed' which will auto install the package

**Comment by pbrisbin** [comment]
> Id like to be able to use downgrade to work with a supplied version number on the commandline

Downgrade has the following two behaviors:

- If you pass `{package}-{version}`, it will limit the results shown
- If you limit the results shown to a single package, it will proceed without prompting

Therefore, as long as you supply something specific enough, it will just downgrade straight away.

Your example seems to work:

```console
% downgrade wine-4.9
wine-4.9-1-x86_64 27.3 MiB  14.3M/s 00:01 [##############################-----------------------]  55
```

> And also an option like 'pacaur --noconfirm --needed' which will auto install the package

Are you talking specifically about `--noconfirm`? I'm not sure if `--needed` would be useful.

Either way, making `downgrade` respect environment variables such as `PACMAN` or `PACMAN_OPTIONS` (or both) would be one way to do this. I would except such a PR, but I'm unlikely to have time to get to it myself.

If I understand the request correctly (please confirm), I'll create an isolated Issue for it and add the appropriate tags. Let me know!

**Comment by winiciuscota** [comment]
Is there anyway to specify whether to use local or remote?

**Comment by pbrisbin** [comment]
Yup, either the searching of the remote archive or the local cache can be disabled by env var, check `man downgrade`.

**Comment by pbrisbin** [comment]
Closing as stale.

It sounds like the Issue as reported is not an Issue, but the following feature did come up:

> > And also an option like 'pacaur --noconfirm --needed' which will auto install the package
>
> Are you talking specifically about --noconfirm? I'm not sure if --needed would be useful.
> 
> ... making downgrade respect environment variables such as PACMAN or PACMAN_OPTIONS (or both) would be one way to do this.

Anyone interested should feel free to create a separate Issue with details on this feature request.

**Comment by atreyasha** [comment]
@Gibbz

>Id like to be able to use downgrade to work with a supplied version number on the commandline.

With #117, we now have version filtering operators which can perform such operations. See the readme for some examples.

>And also an option like 'pacaur --noconfirm --needed' which will auto install the package

After merging #118, we should be able to implement auto-installation (without further prompts).

@winiciuscota 

>Is there anyway to specify whether to use local or remote?

With #102, we provide command-line options for this, specifically with `--cached-only` and `--ala-only`. Check the readme or man-page for further instructions.
