### ISSUE TITLE
Not showing packages with versions starting with lowercased r

### ISSUE THREAD

**Issue by lilydjwg** [pbrisbin/downgrade#92]
It fails to show package files from my cache for a particular package and I find this:

https://github.com/pbrisbin/downgrade/blob/1f4a7459a0f3593c9b6c4e8c11d41751e2c3f959/downgrade#L91

I have no packages starting with an uppercased `R` but several of my -git packages start with a lowercased `r` (there are a few `r*` in [community] too). Also lshw starts with `B`, 0ad starts with `a`, bettercap-caplets starts with `v`, coxeter starts with `git`. This pattern seems too restrictive.

**Comment by pbrisbin** [comment]
Thanks for reporting this; I agree it's too restrictive if you've found such examples. Unfortunately, I think we do need to have _something_ restrictive here. The original intent was to solve the bug where searching for (e.g.) `foo` would return, not just `foo-$version`, but also packages such as `foo-bar-$version`.

It's an annoying problem to find a pattern that works for your examples but doesn't introduce such false positives. We could try to extend that pattern, or maybe there's a way to re-structure the program more substantially and solve the problem another way -- I'm not sure.

Either way, I won't have time to look into this for a bit, so I'm going to add a help-wanted label.
